### ISSUE TITLE
Site-wide management area breaks Elgg admin front-end

### ISSUE THREAD

**Issue by insideth** [hypeJunction/hypeCategories#23]
![image](https://cloud.githubusercontent.com/assets/6679837/6244110/0866dce0-b74f-11e4-822d-ed8f2ee72831.png)

**Comment by hypeJunction** [comment]
Try the latest dev branch. I think I have fixed it.

**Comment by insideth** [comment]
Still fails.Tested from -dev package.

**Comment by hypeJunction** [comment]
Management interface is out of admin area.
