### ISSUE TITLE
icons are rendered incorrectly in elgg 1.11.2

### ISSUE THREAD

**Issue by propertunist** [hypeJunction/hypeCategories#25]
i am testing the github master of hypeCategories here in elgg 1.11.2. 
as you can see in the image below, the icons are not being rendered correctly:
![Image of icons](http://i.imgur.com/xIoLYby.png)

**Comment by propertunist** [comment]
this is more of a problem than i thought, as i am not able to add new categories

**Comment by hypeJunction** [comment]
Add fontawesome to your theme.

**Comment by propertunist** [comment]
ok yes, that resolved the problem. the only issue now is that because the hype categories page is shown outside of the admin context, i am forced to load fontawesome in my public site/theme - even though it is only used in the admin section, which is not so efficient. it would be helpful if the category management page could be moved back to the admin area.

**Comment by hypeJunction** [comment]
Can't move the categories back to admin area, as there are group categories to be managed as well. My suggestion is to extend the manage view and load font awesome there, so replace the css with custom icosn.
