### ISSUE TITLE
categories input list sometimes is unclickable

### ISSUE THREAD

**Issue by propertunist** [hypeJunction/hypeCategories#26]
possibly more than 50% of the time now i am seeing that the triangular sub-tree / node markers in the  list of categories that is shown on item edit pages, such as videolist and elsewhere does not respond to clicks.
i'm fairly sure i have also seen cases where the square input checkboxes also are unclickable. i am not sure why this is yet - i am using firefox.

**Comment by hypeJunction** [comment]
Anything in the console log? It's JS-driven, so if there are any AMD errors, this will not work.

**Comment by propertunist** [comment]
i don't think so.. i am attempting to trigger the problem again to check, but now the problem is not occurring ;)

**Comment by propertunist** [comment]
so i just saw this again and there is zero output in the browser console.

**Comment by hypeJunction** [comment]
Can't reproduce now. Please reopen, if you still see the issue.
