### ISSUE TITLE
enabling group categories breaks links for categories

### ISSUE THREAD

**Issue by propertunist** [hypeJunction/hypeCategories#28]
i just noticed that the target urls for categories on my site were pointing to: mysite.org/categories/group/view/guid/category_name

this was resulting in a 'page not found' page being shown. 
when i disabled the 'enable group categories' option in the admin panel, this was resolved.
i don't know what 'enable group categories' is intended to do, but for me it is breaking category links.

**Comment by hypeJunction** [comment]
Resolved in dev.
