### ISSUE TITLE
Problem with custom category subtypes

### ISSUE THREAD

**Issue by insideth** [hypeJunction/hypeCategories#30]
Hi Ismayil, I added one custom subtype:

File: classes\hypeJunction\Categories\Config.php

     elgg_set_config('taxonomy_tree_subtypes', array(Category::SUBTYPE,'newsubtype'));

File: activate.php

     use hypeJunction\Categories\Category;
     $subtypes = array(
	\hypeJunction\Categories\Category::SUBTYPE => \hypeJunction\Categories\Category::CLASSNAME, 

	'newsubtype' => \hypeJunction\Categories\Category::CLASSNAME,
);

File deactivate.php

    $subtypes = array(Category::SUBTYPE,'newsubtype');

BUT items within categories with this new subtype are not listed from:

http://site.com/categories/view/221/cat-newsubtype

So... I´m doing somenthing wrong?, or problem comes from a plugin error?

**Comment by hypeJunction** [comment]
Sorry for not responding earlier. I have this running just fine on a client site after an upgrade, so the only thing I can think of is race conditions. Try using the `'get_subtypes', 'framework:categories'` hook instead. I will be removing the config options anyway.

**Comment by insideth** [comment]
Where I should use the hook?? In activate.php and deactivate.php?:

elgg_trigger_plugin_hook('get_subtypes', 'framework:categories', null, $subtypes);

I´ve done tens of failed tests. I also tried doing an upgrade. It seems the entity of categories with new subtype are wrong created.

With 3.0.1 release it works, but now with 4.0 one doesn´t work form me.

Thanks Ismayil

**Comment by insideth** [comment]
As a suggestion, maybe you could add an aditional subtype by default in the plugin, it can be very useful like example.

I´ll add an issue with this suggestion, if not you can remove it ;)

**Comment by hypeJunction** [comment]
I am now working on context specific filters, and it will make things
easier. I will add some examples. Basically you will be able to say on
blogs pages, I want to only show blogs and use these category subtypes. It
will automatically generate all the sidebar filters etc.

**Comment by hypeJunction** [comment]
This is working for me, so closing. You can use hooks, like any other hook in Elgg.

**Comment by insideth** [comment]
I´m trying with hypeCategories 4.3.3, added a new custom_category_subtype but items filled in the new category are not listed.

I used this code: 

```
elgg_register_plugin_hook_handler('get_subtypes', 'framework:categories', function($hook, $type, $return, $params) {
    $return[] = 'hjeventmanager';
    return $return;
});
```
Y forgot something?

![captura](https://cloud.githubusercontent.com/assets/6679837/10844247/707b5028-7efe-11e5-8fe1-cfe44d32b1cb.PNG)

**Comment by insideth** [comment]
SOLVED adding the entity view in views/default/object/hjeventmanager.php
