### ISSUE TITLE
Can´t add subcategories from Manage categories area

### ISSUE THREAD

**Issue by insideth** [hypeJunction/hypeCategories#35]
Tested on 4.2.0 release.

![captura](https://cloud.githubusercontent.com/assets/6679837/10850304/19ee3596-7f25-11e5-8f47-3733d1700eda.PNG)

**Comment by hypeJunction** [comment]
It doesn't let you drag into a subcategory position?

**Comment by insideth** [comment]
It does!, I initially tryed to anidate different subtype categories
